version: "3.7"
services:
  chat-database:
    image: mysql:8
    container_name: chat-mysql
    restart: always
    environment:
      MYSQL_DATABASE: chat_application
      MYSQL_ROOT_PASSWORD: siwar
    ports:
      - "3305:3306"
    volumes:
      - /var/lib/mysql/chat-data:/var/lib/mysql